name: Semgrep Full Scan----ne2

on: push
jobs:

  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:

      # step 1
      - name: clone application source code
        uses: actions/checkout@v4

      # step 2
      - name: full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      # step 3

      - name: save report as pipeline artifact
        uses: actions/checkout@v4
        with:
          name: report.sarif
          path: report.sarif

      # step 4
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: report.sarif
          run-id: ${{ github.event.workflow_run.id }}
